"""
LLM-based democratic topic naming module.

Uses an LLM (via the OpenAI API) to generate candidate names for each topic,
then selects the most frequent name across N iterations (democratic voting).
"""

import time
from collections import Counter
from typing import Dict, List, Optional

from openai import OpenAI


class TopicNamer:
    """
    Names topics using democratic LLM voting.

    For each topic (defined by its representative words), the LLM is prompted
    N times to suggest a concise name. The name with the most votes wins.

    Args:
        model: OpenAI model name. Default: "gpt-4o".
        n_votes: Number of independent LLM calls per topic. Default: 100.
            (The original methodology uses 5000; reduce for speed/cost.)
        temperature: Sampling temperature. Default: 0.5.
        max_retries: Max retries per API call on error. Default: 5.
        api_key: OpenAI API key. If None, reads from OPENAI_API_KEY env var.
        domain_context: Context string describing the corpus domain.
            Example: "tweets generated by alcohol companies during COVID-19"
    """

    def __init__(
        self,
        model: str = "gpt-4o",
        n_votes: int = 100,
        temperature: float = 0.5,
        max_retries: int = 5,
        api_key: Optional[str] = None,
        domain_context: str = "a text corpus",
    ):
        self.client = OpenAI(api_key=api_key) if api_key else OpenAI()
        self.model = model
        self.n_votes = n_votes
        self.temperature = temperature
        self.max_retries = max_retries
        self.domain_context = domain_context

    def _get_single_name(self, words: List[str]) -> Optional[str]:
        """Make a single API call to name a topic."""
        prompt = (
            f"The following words represent a topic derived from {self.domain_context}: "
            f"{', '.join(words)}. "
            f"Please provide a concise, meaningful topic name that clearly summarizes these words."
        )

        retries = 0
        while retries < self.max_retries:
            try:
                response = self.client.chat.completions.create(
                    model=self.model,
                    messages=[
                        {"role": "system", "content": "You are an expert at naming topics. Respond with only the topic name, nothing else."},
                        {"role": "user", "content": prompt},
                    ],
                    max_tokens=15,
                    temperature=self.temperature,
                )
                return response.choices[0].message.content.strip()
            except Exception as e:
                retries += 1
                if retries < self.max_retries:
                    time.sleep(2 ** retries)
                else:
                    print(f"Failed after {self.max_retries} retries: {e}")
                    return None

    def name_topic(self, words: List[str], show_progress: bool = False) -> Dict:
        """
        Name a single topic using democratic voting.

        Args:
            words: List of representative words for the topic.
            show_progress: Show progress bar.

        Returns:
            Dict with 'name' (winning name), 'votes' (vote count),
            'total_votes' (total valid votes), and 'all_candidates' (Counter).
        """
        votes = Counter()
        iterator = range(self.n_votes)
        if show_progress:
            from tqdm import tqdm
            iterator = tqdm(iterator, desc=f"Naming topic ({', '.join(words[:3])}...)")

        for _ in iterator:
            name = self._get_single_name(words)
            if name:
                votes[name] += 1

        if not votes:
            return {"name": "Unnamed Topic", "votes": 0, "total_votes": 0, "all_candidates": votes}

        winner, count = votes.most_common(1)[0]
        return {
            "name": winner,
            "votes": count,
            "total_votes": sum(votes.values()),
            "all_candidates": votes,
        }

    def name_all_topics(self, topic_words: Dict[int, List[str]], show_progress: bool = True) -> Dict[int, Dict]:
        """
        Name all topics from a BERTopic model.

        Args:
            topic_words: Dict mapping topic_id -> list of representative words.
                Can be extracted from BERTopic via:
                  {tid: [w for w, _ in model.get_topic(tid)] for tid in model.get_topics() if tid != -1}
            show_progress: Show progress.

        Returns:
            Dict mapping topic_id -> naming result dict.
        """
        results = {}
        for topic_id, words in topic_words.items():
            if show_progress:
                print(f"\nNaming Topic {topic_id}: {words[:5]}...")
            results[topic_id] = self.name_topic(words, show_progress=show_progress)
            if show_progress:
                print(f"  -> '{results[topic_id]['name']}' ({results[topic_id]['votes']}/{results[topic_id]['total_votes']} votes)")
        return results
